sudo: false

language: scala

jdk:
  - oraclejdk8

script: 
  - sbt ++2.11.8 scalastyle compile test:compile test
  - sbt ++2.11.8 docs/tut
  - sbt ++2.11.8 docs_cats/tut
  - sbt ++2.10.6    core/test h2/test hikari/test postgres/test specs2/test
  - sbt ++2.12.0-M4 core/test h2/test hikari/test postgres/test specs2/test

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database world;' -U postgres
  - psql -c '\i world.sql' -d world -U postgres
  - psql -d world -c "create extension postgis" -U postgres
  - psql -d world -c "create type myenum as enum ('foo', 'bar')" -U postgres

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0d4c1d733e9259a3db54
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

