sudo: false

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8
  - 2.12.1

env:
  global:
    - MAIN_SCALA_VERSION=2.11.8

addons:
  postgresql: "9.3"

before_script:
  - project/travis-before-build.sh

script:
  - project/travis-build.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0d4c1d733e9259a3db54
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
