language: scala

jdk:
  - openjdk8

before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.4

install:
  - rvm use 2.6 --install --fuzzy
  - gem install sass
  - gem install jekyll -v 3.2.1

before_script:
  - project/travis-before-build.sh

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - script:
      - sbt +test
      - sbt -J-XX:+UseG1GC docs/mdoc
    - stage: release
      script: sbt ci-release

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.cache/coursier
  - $HOME/.rvm/
  - vendor/bundle

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.cache/coursier -name "*.lock" -type f -delete
