version: '3.1'

services:

  postgres:
    image: postgis/postgis:11-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world
    ports:
      - 5432:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
