version: '3.1'

services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world
    ports:
      - 5432:5432
    volumes:
      - ./init/postgres/:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          memory: 500M


  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: world
    ports:
      - 3306:3306
    volumes:
      - ./init/mysql/:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          memory: 500M
