name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: 8
      - name: Cache SBT
        uses: coursier/cache-action@v3
      - name: Start up Postgres
        run: docker-compose up -d
      - name: Run tests
        run: sbt headerCheck +test docs/makeSite
      - name: Shut down Postgres
        run: docker-compose down
